#!/bin/bash
#wrapper to generate sorted tags file in same dir
if [ -z $1 ];then
	echo "source directory containing js files is required argument"
	exit 1
fi
SRC=$1
if [ -z $2 ];then
	echo "output directory is required as second argument"
	exit 1
fi
OUTPUT_DIR=$2
#the scripts are in EXT_HOME
EXT=$EXT_HOME
INFO_FILE="$OUTPUT_DIR/info"
TMP_FILE="$OUTPUT_DIR/tmp.tags"
rm $INFO_FILE
touch $INFO_FILE

$EXT/genExtTags $SRC $INFO_FILE >  $TMP_FILE

$EXT/replacePointers.pl $TMP_FILE > $OUTPUT_DIR/tags_tmp

#replace signatures of subclass constructors with superclass
$EXT/replaceSignatures.pl $OUTPUT_DIR/tags_tmp > $OUTPUT_DIR/tags

rm $TMP_FILE
