#!/bin/bash
#wrapper to generate sorted tags file in same dir
if [ -z $1 ];then
	echo "source directory containing js files is required argument"
	exit 1
fi
SRC=$1
#the scripts are in EXT_HOME
EXT=$EXT_HOME
INFO_FILE="$EXT/info"
TMP_FILE="${EXT}/tmp.tags"
rm $INFO_FILE
touch $INFO_FILE

$EXT/genExtTags $SRC $INFO_FILE >  $TMP_FILE

$EXT/replacePointers.pl $TMP_FILE > $EXT/tags

rm $TMP_FILE
