#!/bin/bash
#wrapper to generate sorted tags file in same dir
if [ -z $1 ];then
	echo "source directory containing js files is required argument"
	exit 1
fi
SRC=$1
TMP_FILE="tmp.tags"
./genExtTags $SRC >  $TMP_FILE
./replacePointers.pl $TMP_FILE > tags
rm $TMP_FILE
